modLoader="javafml" #mandatory`

loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="${mod_license}"

[[mods]] #mandatory
# The modid of the mod
modId="ben_10_magic_addon" #mandatory

version="${mod_version}" #mandatory

displayName="${mod_name}" #mandatory

credits="${mod_credits}" #optional

authors="${mod_authors}" #optional

description='''${mod_description}'''

[[dependencies.ben_10_magic_addon]] #optional

modId="forge" #mandatory

mandatory=true #mandatory

versionRange="47.2.20" #mandatory

ordering="NONE"

side="BOTH"

[[dependencies.ben_10_magic_addon]]
modId="minecraft"
mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="1.20,1.21"
ordering="NONE"
side="BOTH"
[[dependencies.ben_10_magic_addon]]
modId="irons_spellbooks"
mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="1.20.1-3.0.1, "
ordering="NONE"
side="BOTH"
[[dependencies.ben_10_magic_addon]]
modId="playeranimator" #mandatory
mandatory=true #mandatory
versionRange="[1.0.2-rc1+1.20, )" #mandatory
ordering="AFTER"
side="BOTH"
[[dependencies.ben_10_magic_addon]]
modId="geckolib" #mandatory
mandatory=true #mandatory
versionRange="[4.4.2, )" #mandatory
ordering="NONE"
side="BOTH"
[[dependencies.ben_10_magic_addon]]
modId="curios" #mandatory
mandatory=true #mandatory
versionRange="[5.4.7+1.20.1, )" #mandatory
ordering="NONE"
side="BOTH"
[[dependencies.ben_10_magic_addon]]
modId="caelus" #mandatory
mandatory=true #mandatory
versionRange="[3.1.0+1.20, )" #mandatory
ordering="NONE"
side="BOTH"
